pool:
  vmImage: 'ubuntu-latest'

variables:
  TEST_ENV: 'qa'
  NODE_VERSION: '18.x'

steps:
- checkout: self

- task: NodeTool@0
  inputs:
    versionSpec: '$(NODE_VERSION)'

- script: |
    npm ci
    npx playwright install --with-deps
  displayName: 'Install dependencies and browsers'

- script: |
    npm run regressionTest
  env:
    TEST_ENV: $(TEST_ENV)
  displayName: 'Run Playwright tests'

# publish HTML/Allure artifacts for inspection
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'reports'
    artifactName: 'playwright-reports'
